# Generated by Django 5.1 on 2024-09-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
