# Generated by Django 5.0.4 on 2024-08-23 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_address_line1_userprofile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lattitued',
            new_name='latitued',
        ),
    ]
