# Generated by Django 5.0.3 on 2024-03-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'catagory', 'verbose_name_plural': 'catagories'},
        ),
    ]
