# Generated by Django 5.1 on 2024-10-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_payment_method_remove_order_phone_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor_data',
            field=models.JSONField(blank=True, help_text="Data format: {'vendor_id': {'subtotal': subtotal, 'tax_total': tax_total, 'total': total, 'tax_dict': {'tax_type': {'tax_percentage': percentage, 'tax_amount': amount}}}}", null=True),
        ),
    ]
