# Generated by Django 5.1 on 2024-10-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_vendor_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_tax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderedfood',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderedfood',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(),
        ),
    ]
